In [4]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
print(type(a),a.shape,a[0],a[1],a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b[0]

array([1, 2, 3])

In [ ]:
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

(2, 3)
1 2 4


In [ ]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b=np.ones((1,2))
print(b)

[[1. 1.]]


In [ ]:
c=np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [ ]:
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
e=np.random.random((2,2))
print(e)

[[0.96106096 0.65110354]
 [0.53473547 0.93396942]]


# Array indexing

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
b=a[:2,1:3]
print(b)

[[2 3]
 [5 6]]


In [ ]:
print(a[0,1])

2


In [ ]:
b[0,0]=77
print(a[0,1])

77


In [ ]:
print(a)
print(b)

[[ 1 77  3]
 [ 4  5  6]
 [ 7  8  9]]
[[77  3]
 [ 5  6]]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
r1=a[1,:]
print(r1,r1.shape)

[4 5 6] (3,)


In [ ]:
r2=a[1:2,:]
print(r2,r2.shape)

[[4 5 6]] (1, 3)


In [ ]:
r3=a[[1],:]
print(r3,r3.shape)

[[4 5 6]] (1, 3)


In [ ]:
c1=a[:,1]
print(c1,c1.shape)

[2 5 8] (3,)


In [ ]:
c2=a[:,1:2]
print(c2,c2.shape)

[[2]
 [5]
 [8]] (3, 1)


In [5]:
a=np.array([[1,2],[3,4],[5,6]])
print(a.shape)

(3, 2)


In [ ]:
print(a[[0,1,2],[0,1,0]])

[1 4 5]


In [ ]:
print(np.array([[0,0],a[1,1],[2,0]]))

[list([0, 0]) 4 list([2, 0])]


<ipython-input-28-bde55d8bb0ce>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.array([[0,0],a[1,1],[2,0]]))


In [ ]:
print(np.array([a[0,1],a[0,1]]))

[2 2]


In [6]:
a=np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])
print(a)

[[1 2 3]
 [3 4 5]
 [5 6 7]
 [7 8 9]]


In [8]:
b=np.array([0,2,0,1])
print(b)

[0 2 0 1]


In [ ]:
print(a[:,b])

[[1 3 1 2]
 [3 5 3 4]
 [5 7 5 6]
 [7 9 7 8]]


In [9]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)
bool_idx=(a>2)
print(a[a>2])

[[1 2]
 [3 4]
 [5 6]]
[3 4 5 6]


In [10]:
print(a[bool_idx])
print(a[a>2])

[3 4 5 6]
[3 4 5 6]


In [11]:
x=np.array([1,2])
y=np.array([1.0,2.0])
z=np.array([1,2],dtype=np.int64)
print(x.dtype,y.dtype,z.dtype)

int64 float64 int64


# **Array math**

In [12]:
x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [13]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [14]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [15]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [16]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [18]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
v=np.array([9,10])
w=np.array([11,12])
print(v.shape,w.shape)
print(v.dot(w))
print(np.dot(v,w))
print(x.dot(y))

(2,) (2,)
219
219
[[19 22]
 [43 50]]


In [19]:
z=np.eye(2)
print(x.dot(z))

[[1. 2.]
 [3. 4.]]


In [20]:
print(v@w)

219


In [21]:
print(x.dot(v))
print(np.dot(x,v))
print(x@y)

[29 67]
[29 67]
[[19 22]
 [43 50]]


In [22]:
x=np.array([[1,2],[3,4]])
print(np.sum(x))

10


In [23]:
print(x)
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

[[1 2]
 [3 4]]
[4 6]
[3 7]


In [24]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [25]:
v=np.array([[1,2,3]])
print(v.shape)
print(v)
print("transpose\n", v.T)

(1, 3)
[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


In [27]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
y=np.empty_like(x)
for i in range(4):
  y[i,:]=x[i,:]+v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [29]:
vv=np.tile(v,(4,1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [30]:
y=x+vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [31]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
y=x+v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [32]:
v=np.array([1,2,3])
w=np.array([4,5])
print(np.reshape(v, (3,1))*w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [33]:
x=np.array([[1,2,3],[4,5,6]])
print(x+v)

[[2 4 6]
 [5 7 9]]


In [34]:
print((x.T+w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [38]:
print(x*2)

[[ 2  4  6]
 [ 8 10 12]]
